# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_KEY_CONTENT"),
      is_key_content_base64: true
    )
  end

  private_lane :build_and_upload do |options|
    scheme = options.fetch(:scheme)
    configuration = options.fetch(:configuration)
    app_identifier = options.fetch(:app_identifier)
    fr_changelog = options[:fr_changelog] || ENV["FR_CHANGELOG"]
    en_changelog = options[:en_changelog] || ENV["EN_CHANGELOG"]

    build_app(
      project: "code.xcodeproj",
      scheme: scheme,
      configuration: configuration,
      clean: true,
      output_directory: "builds/#{scheme}",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

    if options[:publish_testflight]
      upload_to_testflight(
        api_key: asc_api_key,
        app_identifier: app_identifier,
        skip_waiting_for_build_processing: true
      )
    end

    if options[:publish_app_store]
      release_notes = { "en-US" => en_changelog, "fr-FR" => fr_changelog }
      support_url = {
        "en-US" => "https://codedorian.com",
        "fr-FR" => "https://codedorian.com"
      }
      copyright_notice = "#{Time.now.year} codedorian.com"

      upload_to_app_store(
        api_key: asc_api_key,
        app_identifier: app_identifier,
        release_notes: release_notes,
        support_url: support_url,
        copyright: copyright_notice,
        precheck_include_in_app_purchases: false,
        force: true,
        skip_binary_upload: true,
        skip_metadata: false,
        skip_screenshots: true
      )
    end
  end

  desc "Build and upload TestFlight for test"
  lane :test do |options|
    build_and_upload(
      scheme: "test",
      configuration: "test",
      app_identifier: "com.codedorian.test",
      publish_testflight: true
    )
  end

  desc "Build and upload TestFlight for localhost"
  lane :localhost do |options|
    build_and_upload(
      scheme: "localhost",
      configuration: "localhost",
      app_identifier: "com.codedorian.localhost",
      publish_testflight: true
    )
  end

  desc "Build and upload TestFlight for development"
  lane :development do |options|
    build_and_upload(
      scheme: "development",
      configuration: "development",
      app_identifier: "com.codedorian.development",
      publish_testflight: true
    )
  end

  desc "Build and upload TestFlight for staging"
  lane :staging do |options|
    build_and_upload(
      scheme: "staging",
      configuration: "staging",
      app_identifier: "com.codedorian.staging",
      publish_testflight: true
    )
  end

  desc "Build and upload TestFlight for production"
  lane :production do |options|
    build_and_upload(
      scheme: "production",
      configuration: "production",
      app_identifier: "com.codedorian",
      en_changelog: options[:en_changelog],
      fr_changelog: options[:fr_changelog],
      publish_testflight: true,
      publish_app_store: true
    )
  end
end
