# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_KEY_CONTENT"),
      is_key_content_base64: true
    )
  end

  private_lane :build_and_upload do |options|
    scheme = options.fetch(:scheme)
    configuration = options.fetch(:configuration)
    app_identifier = options.fetch(:app_identifier)

    build_app(
      project: "code.xcodeproj",
      scheme: scheme,
      configuration: configuration,
      clean: true,
      output_directory: "builds/#{scheme}",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: asc_api_key,
      app_identifier: app_identifier,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload TestFlight for test"
  lane :test do
    build_and_upload(
      scheme: "test",
      configuration: "test",
      app_identifier: "com.codedorian.test"
    )
  end

  desc "Build and upload TestFlight for localhost"
  lane :localhost do
    build_and_upload(
      scheme: "localhost",
      configuration: "localhost",
      app_identifier: "com.codedorian.localhost"
    )
  end

  desc "Build and upload TestFlight for development"
  lane :development do
    build_and_upload(
      scheme: "development",
      configuration: "development",
      app_identifier: "com.codedorian.development"
    )
  end

  desc "Build and upload TestFlight for staging"
  lane :staging do
    build_and_upload(
      scheme: "staging",
      configuration: "staging",
      app_identifier: "com.codedorian.staging"
    )
  end

  desc "Build and upload TestFlight for production"
  lane :production do
    build_and_upload(
      scheme: "production",
      configuration: "production",
      app_identifier: "com.codedorian"
    )
  end
end
